version: "3"

services:
  # Alpine Linux
  alpinelinux: # https://hub.docker.com/_/alpine
    container_name: dotfiles-alpinelinux
    build:
      context: ./.docker/alpine/alpinelinux
      dockerfile: Dockerfile

  # Arch Linux
  archlinux: # https://hub.docker.com/_/archlinux
    container_name: dotfiles-archlinux
    build:
      context: ./
      dockerfile: ./.docker/arch/archlinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    volumes:
      - ./dotfiles/.default-python-packages:/home/${USER}/.default-python-packages
      - ./dotfiles/.gitconfig:/home/${USER}/.gitconfig
      - ./dotfiles/.p10k.zsh:/home/${USER}/.p10k.zsh
      - ./dotfiles/.tool-versions:/home/${USER}/.tool-versions
      - ./dotfiles/.vimrc:/home/${USER}/.vimrc
      - ./dotfiles/.zimrc:/home/${USER}/.zimrc
      - ./dotfiles/.zshrc:/home/${USER}/.zshrc
    tty: true

  # Debian
  debian: # https://hub.docker.com/_/debian
    container_name: dotfiles-debian
    build:
      context: ./
      dockerfile: ./.docker/debian/debian/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    volumes:
      - ./dotfiles/.default-python-packages:/home/${USER}/.default-python-packages
      - ./dotfiles/.gitconfig:/home/${USER}/.gitconfig
      - ./dotfiles/.p10k.zsh:/home/${USER}/.p10k.zsh
      - ./dotfiles/.tool-versions:/home/${USER}/.tool-versions
      - ./dotfiles/.vimrc:/home/${USER}/.vimrc
      - ./dotfiles/.zimrc:/home/${USER}/.zimrc
      - ./dotfiles/.zshrc:/home/${USER}/.zshrc
    tty: true
  ubuntu: # https://hub.docker.com/_/ubuntu
    container_name: dotfiles-ubuntu
    build:
      context: ./
      dockerfile: ./.docker/debian/ubuntu/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    volumes:
      - ./dotfiles/.default-python-packages:/home/${USER}/.default-python-packages
      - ./dotfiles/.gitconfig:/home/${USER}/.gitconfig
      - ./dotfiles/.p10k.zsh:/home/${USER}/.p10k.zsh
      - ./dotfiles/.tool-versions:/home/${USER}/.tool-versions
      - ./dotfiles/.vimrc:/home/${USER}/.vimrc
      - ./dotfiles/.zimrc:/home/${USER}/.zimrc
      - ./dotfiles/.zshrc:/home/${USER}/.zshrc
    tty: true

  # Red Hat
  almalinux: # https://hub.docker.com/_/almalinux
    container_name: dotfiles-almalinux
    build:
      context: ./
      dockerfile: ./.docker/redhat/almalinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    volumes:
      - ./dotfiles/.default-python-packages:/home/${USER}/.default-python-packages
      - ./dotfiles/.gitconfig:/home/${USER}/.gitconfig
      - ./dotfiles/.p10k.zsh:/home/${USER}/.p10k.zsh
      - ./dotfiles/.tool-versions:/home/${USER}/.tool-versions
      - ./dotfiles/.vimrc:/home/${USER}/.vimrc
      - ./dotfiles/.zimrc:/home/${USER}/.zimrc
      - ./dotfiles/.zshrc:/home/${USER}/.zshrc
    tty: true
  amazonlinux: # https://hub.docker.com/_/amazonlinux
    container_name: dotfiles-amazonlinux
    build:
      context: ./
      dockerfile: ./.docker/redhat/amazonlinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    volumes:
      - ./dotfiles/.default-python-packages:/home/${USER}/.default-python-packages
      - ./dotfiles/.gitconfig:/home/${USER}/.gitconfig
      - ./dotfiles/.p10k.zsh:/home/${USER}/.p10k.zsh
      - ./dotfiles/.tool-versions:/home/${USER}/.tool-versions
      - ./dotfiles/.vimrc:/home/${USER}/.vimrc
      - ./dotfiles/.zimrc:/home/${USER}/.zimrc
      - ./dotfiles/.zshrc:/home/${USER}/.zshrc
    tty: true
  fedora: # https://hub.docker.com/_/fedora
    container_name: dotfiles-fedora
    build:
      context: ./
      dockerfile: ./.docker/redhat/fedora/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    volumes:
      - ./dotfiles/.default-python-packages:/home/${USER}/.default-python-packages
      - ./dotfiles/.gitconfig:/home/${USER}/.gitconfig
      - ./dotfiles/.p10k.zsh:/home/${USER}/.p10k.zsh
      - ./dotfiles/.tool-versions:/home/${USER}/.tool-versions
      - ./dotfiles/.vimrc:/home/${USER}/.vimrc
      - ./dotfiles/.zimrc:/home/${USER}/.zimrc
      - ./dotfiles/.zshrc:/home/${USER}/.zshrc
    tty: true
  rockylinux: # https://hub.docker.com/_/rockylinux
    container_name: dotfiles-rockylinux
    build:
      context: ./
      dockerfile: ./.docker/redhat/rockylinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    volumes:
      - ./dotfiles/.default-python-packages:/home/${USER}/.default-python-packages
      - ./dotfiles/.gitconfig:/home/${USER}/.gitconfig
      - ./dotfiles/.p10k.zsh:/home/${USER}/.p10k.zsh
      - ./dotfiles/.tool-versions:/home/${USER}/.tool-versions
      - ./dotfiles/.vimrc:/home/${USER}/.vimrc
      - ./dotfiles/.zimrc:/home/${USER}/.zimrc
      - ./dotfiles/.zshrc:/home/${USER}/.zshrc
    tty: true

  # openSUSE
  opensuse: # https://hub.docker.com/r/opensuse/leap
    container_name: dotfiles-opensuse
    build:
      context: ./.docker/suse/opensuse
      dockerfile: Dockerfile
