version: "3"

services:
  # https://upload.wikimedia.org/wikipedia/commons/1/1b/Linux_Distribution_Timeline.svg

  # Alpine Linux
  alpinelinux: # https://hub.docker.com/_/alpine
    container_name: dotfiles-alpinelinux
    build:
      context: ./
      dockerfile: ./.docker/alpine/alpinelinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    tty: true

  # Arch Linux
  archlinux: # https://hub.docker.com/_/archlinux
    container_name: dotfiles-archlinux
    build:
      context: ./
      dockerfile: ./.docker/arch/archlinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    tty: true

  # Debian
  debian: # https://hub.docker.com/_/debian
    container_name: dotfiles-debian
    build:
      context: ./
      dockerfile: ./.docker/debian/debian/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    tty: true
  kalilinux: # https://hub.docker.com/r/kalilinux/kali-rolling
    container_name: dotfiles-kalilinux
    build:
      context: ./
      dockerfile: ./.docker/debian/kalilinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    tty: true
  ubuntu: # https://hub.docker.com/_/ubuntu
    container_name: dotfiles-ubuntu
    build:
      context: ./
      dockerfile: ./.docker/debian/ubuntu/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    tty: true

  # Red Hat
  almalinux: # https://hub.docker.com/_/almalinux
    container_name: dotfiles-almalinux
    build:
      context: ./
      dockerfile: ./.docker/redhat/almalinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    tty: true
  amazonlinux: # https://hub.docker.com/_/amazonlinux
    container_name: dotfiles-amazonlinux
    build:
      context: ./
      dockerfile: ./.docker/redhat/amazonlinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    tty: true
  fedora: # https://hub.docker.com/_/fedora
    container_name: dotfiles-fedora
    build:
      context: ./
      dockerfile: ./.docker/redhat/fedora/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    tty: true
  rockylinux: # https://hub.docker.com/_/rockylinux
    container_name: dotfiles-rockylinux
    build:
      context: ./
      dockerfile: ./.docker/redhat/rockylinux/Dockerfile
      args:
        - WORK_USER=${USER}
        - WORK_GROUP=${USER}
        - WORK_UID=${WORK_UID}
        - WORK_GID=${WORK_GID}
    tty: true
