# ================================================================================
#  __________________________________________
#   __________________________________________
#    _____________________________/\\\_________
#     ____________________________\/\\\_________
#      ____________________________\/\\\_________
#       __/\\\\\\\\\\\__/\\\\\\\\\\_\/\\\_________
#        _\///////\\\/__\/\\\//////__\/\\\\\\\\\\__
#         ______/\\\/____\/\\\\\\\\\\_\/\\\/////\\\_
#          ____/\\\/______\////////\\\_\/\\\___\/\\\_
#           __/\\\\\\\\\\\__/\\\\\\\\\\_\/\\\___\/\\\_
#            _\///////////__\//////////__\///____\///__
#             __________________________________________
#              __________________________________________
#               __________________________________________
# ================================================================================

# --------------------------------------------------------------------------------
# init
# --------------------------------------------------------------------------------

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# --------------------------------------------------------------------------------
# PATH
# --------------------------------------------------------------------------------
export PATH="/home/linuxbrew/.linuxbrew/bin:$HOME/bin:$PATH"

# --------------------------------------------------------------------------------
# nvm
# --------------------------------------------------------------------------------
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# --------------------------------------------------------------------------------
# zplug
# --------------------------------------------------------------------------------
## init
if [[ -n $(uname | grep -i 'Darwin') ]] ; then
  export ZPLUG_HOME="/usr/local/opt/zplug"
else
  export ZPLUG_HOME="/home/linuxbrew/.linuxbrew/opt/zplug"
fi
source $ZPLUG_HOME/init.zsh

## plugins
zplug "romkatv/powerlevel10k", as:theme, depth:1       # プロンプトのカスタマイズ
zplug "zsh-users/zsh-syntax-highlighting", defer:2     # コマンドに色付けする
zplug "zsh-users/zsh-autosuggestions"                  # 薄い色で直近の履歴を表示する
zplug "zsh-users/zsh-completions"                      # 補完を詳細に表示する
zplug "Aloxaf/fzf-tab"                                 # fzf で 入力補完を強化する
zplug "b4b4r07/enhancd", use:init.sh                   # fzf で cd を強化する
zplug "wfxr/forgit"                                    # fzf で git を強化する
zplug "bigH/git-fuzzy", as:command, use:bin/git-fuzzy  # fzf で git を強化する

# --------------------------------------------------------------------------------
# os差分
# --------------------------------------------------------------------------------
if [[ -n $(uname | grep -i 'Darwin') ]] ; then
  # 'MacOS'

elif [[ -n $( uname | grep -i 'Linux' ) ]] && [[ -z $( uname -r | grep -i 'microsoft' ) ]] ; then
  # 'Linux'

elif [[ -n $( uname | grep -i 'Linux' ) ]] && [[ -n $( uname -r | grep -i 'microsoft' ) ]] ; then
  # 'WSL'
  ## ディスプレイ設定
  export WSL_ip_line=$(ipconfig.exe | grep "WSL" -n | awk -F ":" '{print $1+4}')
  export DISPLAY=$(ipconfig.exe | awk -v a=$WSL_ip_line '{if (NR==a) print $NF":0.0"}' | tr -d "\r")
  export WINDOWS_USERNAME=$(cd /mnt/c && cmd.exe /c 'echo %USERNAME%' | awk '{ print $1 }' | tr -d "\r")

else
  # 'Windows'

fi

# --------------------------------------------------------------------------------
# 各設定ファイル
# --------------------------------------------------------------------------------
# link
for file in $HOME/.dotfiles/tag-zsh/*.zsh(.N); do
  source $file
done

# --------------------------------------------------------------------------------
# local用
# --------------------------------------------------------------------------------
[[ ! -f ~/.zshrc.local ]] || source ~/.zshrc.local

# --------------------------------------------------------------------------------
# zplug install
# --------------------------------------------------------------------------------
zplug check --verbose || zplug install
zplug load
export PYENV_ROOT="${HOME}/.pyenv"
if [ -d "${PYENV_ROOT}" ]; then
    export PATH=${PYENV_ROOT}/bin:$PATH
    eval "$(pyenv init -)"
fi
